function CreateBlip(gamemode)
    if gamemode == "default_damaged_only_pistol" then
        default_damaged_only_pistol_blip = AddBlipForRadius(default_damaged_only_pistol_coords.x, default_damaged_only_pistol_coords.y, default_damaged_only_pistol_coords.z, 135.0)
        SetBlipHighDetail(default_damaged_only_pistol_blip, true)
        SetBlipColour(default_damaged_only_pistol_blip, 1)
        SetBlipAlpha(default_damaged_only_pistol_blip, 50)
    elseif gamemode == "default_damaged_only_pistol_2" then
        default_damaged_only_pistol_2_blip = AddBlipForRadius(default_damaged_only_pistol_2_coords.x, default_damaged_only_pistol_2_coords.y, default_damaged_only_pistol_2_coords.z, 135.0)
        SetBlipHighDetail(default_damaged_only_pistol_2_blip, true)
        SetBlipColour(default_damaged_only_pistol_2_blip, 1)
        SetBlipAlpha(default_damaged_only_pistol_2_blip, 50)
    elseif gamemode == "default_damaged_only_ap_pistol" then
        default_damaged_only_ap_pistol_blip = AddBlipForRadius(default_damaged_only_ap_pistol_coords.x, default_damaged_only_ap_pistol_coords.y, default_damaged_only_ap_pistol_coords.z, 135.0)
        SetBlipHighDetail(default_damaged_only_ap_pistol_blip, true)
        SetBlipColour(default_damaged_only_ap_pistol_blip, 1)
        SetBlipAlpha(default_damaged_only_ap_pistol_blip, 50)
    elseif gamemode == "default_damaged_only_ap_pistol_2" then
        default_damaged_only_ap_pistol_2_blip = AddBlipForRadius(default_damaged_only_ap_pistol_2_coords.x, default_damaged_only_ap_pistol_2_coords.y, default_damaged_only_ap_pistol_2_coords.z, 135.0)
        SetBlipHighDetail(default_damaged_only_ap_pistol_2_blip, true)
        SetBlipColour(default_damaged_only_ap_pistol_2_blip, 1)
        SetBlipAlpha(default_damaged_only_ap_pistol_2_blip, 50)
    elseif gamemode == "default_damaged_only_smg" then
        default_damaged_only_smg_blip = AddBlipForRadius(default_damaged_only_smg_coords.x, default_damaged_only_smg_coords.y, default_damaged_only_smg_coords.z, 135.0)
        SetBlipHighDetail(default_damaged_only_smg_blip, true)
        SetBlipColour(default_damaged_only_smg_blip, 1)
        SetBlipAlpha(default_damaged_only_smg_blip, 50)
    elseif gamemode == "default_damaged_only_smg_2" then
        default_damaged_only_smg_2_blip = AddBlipForRadius(default_damaged_only_smg_2_coords.x, default_damaged_only_smg_2_coords.y, default_damaged_only_smg_2_coords.z, 135.0)
        SetBlipHighDetail(default_damaged_only_smg_2_blip, true)
        SetBlipColour(default_damaged_only_smg_2_blip, 1)
        SetBlipAlpha(default_damaged_only_smg_2_blip, 50)
    elseif gamemode == "default_damaged_only_rifle" then
        default_damaged_only_rifle_blip = AddBlipForRadius(default_damaged_only_rifle_coords.x, default_damaged_only_rifle_coords.y, default_damaged_only_rifle_coords.z, 135.0)
        SetBlipHighDetail(default_damaged_only_rifle_blip, true)
        SetBlipColour(default_damaged_only_rifle_blip, 1)
        SetBlipAlpha(default_damaged_only_rifle_blip, 50)
    elseif gamemode == "default_damaged_only_rifle_2" then
        default_damaged_only_rifle_2_blip = AddBlipForRadius(default_damaged_only_rifle_2_coords.x, default_damaged_only_rifle_2_coords.y, default_damaged_only_rifle_2_coords.z, 135.0)
        SetBlipHighDetail(default_damaged_only_rifle_2_blip, true)
        SetBlipColour(default_damaged_only_rifle_2_blip, 1)
        SetBlipAlpha(default_damaged_only_rifle_2_blip, 50)
    elseif gamemode == "custom_damaged_only_pistol" then
        custom_damaged_only_pistol_blip = AddBlipForRadius(custom_damaged_only_pistol_coords.x, custom_damaged_only_pistol_coords.y, custom_damaged_only_pistol_coords.z, 135.0)
        SetBlipHighDetail(custom_damaged_only_pistol_blip, true)
        SetBlipColour(custom_damaged_only_pistol_blip, 1)
        SetBlipAlpha(custom_damaged_only_pistol_blip, 50)
    elseif gamemode == "custom_damaged_only_pistol_2" then
        custom_damaged_only_pistol_2_blip = AddBlipForRadius(custom_damaged_only_pistol_2_coords.x, custom_damaged_only_pistol_2_coords.y, custom_damaged_only_pistol_2_coords.z, 135.0)
        SetBlipHighDetail(custom_damaged_only_pistol_2_blip, true)
        SetBlipColour(custom_damaged_only_pistol_2_blip, 1)
        SetBlipAlpha(custom_damaged_only_pistol_2_blip, 50)
    elseif gamemode == "custom_damaged_only_smg" then
        custom_damaged_only_smg_blip = AddBlipForRadius(custom_damaged_only_smg_coords.x, custom_damaged_only_smg_coords.y, custom_damaged_only_smg_coords.z, 135.0)
        SetBlipHighDetail(custom_damaged_only_smg_blip, true)
        SetBlipColour(custom_damaged_only_smg_blip, 1)
        SetBlipAlpha(custom_damaged_only_smg_blip, 50)
    elseif gamemode == "custom_damaged_only_rifle" then
        custom_damaged_only_rifle_blip = AddBlipForRadius(custom_damaged_only_rifle_coords.x, custom_damaged_only_rifle_coords.y, custom_damaged_only_rifle_coords.z, 135.0)
        SetBlipHighDetail(custom_damaged_only_rifle_blip, true)
        SetBlipColour(custom_damaged_only_rifle_blip, 1)
        SetBlipAlpha(custom_damaged_only_rifle_blip, 50)
    elseif gamemode == "custom_damaged_only_shotgun" then
        custom_damaged_only_shotgun_blip = AddBlipForRadius(custom_damaged_only_shotgun_coords.x, custom_damaged_only_shotgun_coords.y, custom_damaged_only_shotgun_coords.z, 135.0)
        SetBlipHighDetail(custom_damaged_only_shotgun_blip, true)
        SetBlipColour(custom_damaged_only_shotgun_blip, 1)
        SetBlipAlpha(custom_damaged_only_shotgun_blip, 50)
    elseif gamemode == "custom_damaged_only_revolver" then
        custom_damaged_only_revolver_blip = AddBlipForRadius(custom_damaged_only_revolver_coords.x, custom_damaged_only_revolver_coords.y, custom_damaged_only_revolver_coords.z, 135.0)
        SetBlipHighDetail(custom_damaged_only_revolver_blip, true)
        SetBlipColour(custom_damaged_only_revolver_blip, 1)
        SetBlipAlpha(custom_damaged_only_revolver_blip, 50)
    elseif gamemode == "custom_damaged_only_m60" then
        custom_damaged_only_m60_blip = AddBlipForRadius(custom_damaged_only_m60_coords.x, custom_damaged_only_m60_coords.y, custom_damaged_only_m60_coords.z, 135.0)
        SetBlipHighDetail(custom_damaged_only_m60_blip, true)
        SetBlipColour(custom_damaged_only_m60_blip, 1)
        SetBlipAlpha(custom_damaged_only_m60_blip, 50)
    elseif gamemode == "custom_damaged_only_m60_2" then
        custom_damaged_only_m60_2_blip = AddBlipForRadius(custom_damaged_only_m60_2_coords.x, custom_damaged_only_m60_2_coords.y, custom_damaged_only_m60_2_coords.z, 135.0)
        SetBlipHighDetail(custom_damaged_only_m60_2_blip, true)
        SetBlipColour(custom_damaged_only_m60_2_blip, 1)
        SetBlipAlpha(custom_damaged_only_m60_2_blip, 50)
    elseif gamemode == "custom_damaged_only_labirent" then
        custom_damaged_only_labirent_blip = AddBlipForRadius(custom_damaged_only_labirent_coords.x, custom_damaged_only_labirent_coords.y, custom_damaged_only_labirent_coords.z, 135.0)
        SetBlipHighDetail(custom_damaged_only_labirent_blip, true)
        SetBlipColour(custom_damaged_only_labirent_blip, 1)
        SetBlipAlpha(custom_damaged_only_labirent_blip, 50)
    elseif gamemode == "advanced_gungame" then
        if cl_gungame_map_1 then
            advanced_gungame_blip = AddBlipForRadius(advanced_gungame_coords.x, advanced_gungame_coords.y, advanced_gungame_coords.z, 135.0)
            SetBlipHighDetail(advanced_gungame_blip, true)
            SetBlipColour(advanced_gungame_blip, 1)
            SetBlipAlpha(advanced_gungame_blip, 50)
        elseif cl_gungame_map_2 then
            advanced_gungame_blip = AddBlipForRadius(advanced_gungame_coords_2.x, advanced_gungame_coords_2.y, advanced_gungame_coords_2.z, 135.0)
            SetBlipHighDetail(advanced_gungame_blip, true)
            SetBlipColour(advanced_gungame_blip, 1)
            SetBlipAlpha(advanced_gungame_blip, 50)
        elseif cl_gungame_map_3 then
            advanced_gungame_blip = AddBlipForRadius(advanced_gungame_coords_3.x, advanced_gungame_coords_3.y, advanced_gungame_coords_3.z, 135.0)
            SetBlipHighDetail(advanced_gungame_blip, true)
            SetBlipColour(advanced_gungame_blip, 1)
            SetBlipAlpha(advanced_gungame_blip, 50)
        elseif cl_gungame_map_4 then
            advanced_gungame_blip = AddBlipForRadius(advanced_gungame_coords_4.x, advanced_gungame_coords_4.y, advanced_gungame_coords_4.z, 135.0)
            SetBlipHighDetail(advanced_gungame_blip, true)
            SetBlipColour(advanced_gungame_blip, 1)
            SetBlipAlpha(advanced_gungame_blip, 50)
        elseif cl_gungame_map_5 then
            advanced_gungame_blip = AddBlipForRadius(advanced_gungame_coords_5.x, advanced_gungame_coords_5.y, advanced_gungame_coords_5.z, 135.0)
            SetBlipHighDetail(advanced_gungame_blip, true)
            SetBlipColour(advanced_gungame_blip, 1)
            SetBlipAlpha(advanced_gungame_blip, 50)
        elseif cl_gungame_map_6 then
            advanced_gungame_blip = AddBlipForRadius(advanced_gungame_coords_6.x, advanced_gungame_coords_6.y, advanced_gungame_coords_6.z, 135.0)
            SetBlipHighDetail(advanced_gungame_blip, true)
            SetBlipColour(advanced_gungame_blip, 1)
            SetBlipAlpha(advanced_gungame_blip, 50)
        end
    elseif gamemode == "advanced_gungame_2" then
        advanced_gungame_2_blip = AddBlipForRadius(advanced_gungame_2_coords.x, advanced_gungame_2_coords.y, advanced_gungame_2_coords.z, 600.0)
        SetBlipHighDetail(advanced_gungame_2_blip, true)
        SetBlipColour(advanced_gungame_2_blip, 1)
        SetBlipAlpha(advanced_gungame_2_blip, 50)
    elseif gamemode == "advanced_gungame_3" then
        advanced_gungame_3_blip = AddBlipForRadius(advanced_gungame_3_coords.x, advanced_gungame_3_coords.y, advanced_gungame_3_coords.z, 135.0)
        SetBlipHighDetail(advanced_gungame_3_blip, true)
        SetBlipColour(advanced_gungame_3_blip, 1)
        SetBlipAlpha(advanced_gungame_3_blip, 50)
    elseif gamemode == "advanced_gangwar" then
        advanced_gangwar_blip = AddBlipForRadius(advanced_gangwar_coords.x, advanced_gangwar_coords.y, advanced_gangwar_coords.z, 135.0)
        SetBlipHighDetail(advanced_gangwar_blip, true)
        SetBlipColour(advanced_gangwar_blip, 1)
        SetBlipAlpha(advanced_gangwar_blip, 50)
    elseif gamemode == "advanced_farm_fight" then
        advanced_farm_fight_blip = AddBlipForRadius(advanced_farm_fight_coords.x, advanced_farm_fight_coords.y, advanced_farm_fight_coords.z, 135.0)
        SetBlipHighDetail(advanced_farm_fight_blip, true)
        SetBlipColour(advanced_farm_fight_blip, 1)
        SetBlipAlpha(advanced_farm_fight_blip, 50)
    elseif gamemode == "advanced_zombie" then
        advanced_zombie_blip = AddBlipForRadius(advanced_zombie_coords.x, advanced_zombie_coords.y, advanced_zombie_coords.z, 135.0)
        SetBlipHighDetail(advanced_zombie_blip, true)
        SetBlipColour(advanced_zombie_blip, 1)
        SetBlipAlpha(advanced_zombie_blip, 50)
    elseif gamemode == "advanced_sumo" then
        advanced_sumo_blip = AddBlipForRadius(advanced_sumo_coords.x, advanced_sumo_coords.y, advanced_sumo_coords.z, 250.0)
        SetBlipHighDetail(advanced_sumo_blip, true)
        SetBlipColour(advanced_sumo_blip, 1)
        SetBlipAlpha(advanced_sumo_blip, 50)
    elseif gamemode == "advanced_parkour" then
        advanced_parkour_blip = AddBlipForRadius(advanced_parkour_coords.x, advanced_parkour_coords.y, advanced_parkour_coords.z, 250.0)
        SetBlipHighDetail(advanced_parkour_blip, true)
        SetBlipColour(advanced_parkour_blip, 1)
        SetBlipAlpha(advanced_parkour_blip, 50)
    elseif gamemode == "advanced_snowball" then
        advanced_snowball_blip = AddBlipForRadius(advanced_snowball_coords.x, advanced_snowball_coords.y, advanced_snowball_coords.z, 135.0)
        SetBlipHighDetail(advanced_snowball_blip, true)
        SetBlipColour(advanced_snowball_blip, 1)
        SetBlipAlpha(advanced_snowball_blip, 50)
    elseif gamemode == "advanced_knife" then
        advanced_knife_blip = AddBlipForRadius(advanced_knife_coords.x, advanced_knife_coords.y, advanced_knife_coords.z, 135.0)
        SetBlipHighDetail(advanced_knife_blip, true)
        SetBlipColour(advanced_knife_blip, 1)
        SetBlipAlpha(advanced_knife_blip, 50)
    elseif gamemode == "priv_lobby_madde_x" then
        priv_lobby_madde_x_blip = AddBlipForRadius(priv_lobby_madde_x_coords.x, priv_lobby_madde_x_coords.y, priv_lobby_madde_x_coords.z, 135.0)
        SetBlipHighDetail(priv_lobby_madde_x_blip, true)
        SetBlipColour(priv_lobby_madde_x_blip, 1)
        SetBlipAlpha(priv_lobby_madde_x_blip, 50)
    end
end

function DeleteAllBlips()
    RemoveBlip(default_damaged_only_pistol_blip)
    RemoveBlip(default_damaged_only_pistol_2_blip)
    RemoveBlip(default_damaged_only_ap_pistol_blip)
    RemoveBlip(default_damaged_only_ap_pistol_2_blip)
    RemoveBlip(default_damaged_only_smg_blip)
    RemoveBlip(default_damaged_only_smg_2_blip)
    RemoveBlip(default_damaged_only_rifle_blip)
    RemoveBlip(default_damaged_only_rifle_2_blip)
    RemoveBlip(custom_damaged_only_pistol_blip)
    RemoveBlip(custom_damaged_only_pistol_2_blip)
    RemoveBlip(custom_damaged_only_smg_blip)
    RemoveBlip(custom_damaged_only_rifle_blip)
    RemoveBlip(custom_damaged_only_shotgun_blip)
    RemoveBlip(custom_damaged_only_revolver_blip)
    RemoveBlip(custom_damaged_only_m60_blip)
    RemoveBlip(custom_damaged_only_m60_2_blip)
    RemoveBlip(custom_damaged_only_deluxo_blip)
    RemoveBlip(deluxo_safe_blip)
    RemoveBlip(custom_damaged_only_labirent_blip)
    RemoveBlip(advanced_gungame_blip)
    RemoveBlip(advanced_gungame_2_blip)
    RemoveBlip(advanced_gungame_3_blip)
    RemoveBlip(advanced_gangwar_blip)
    RemoveBlip(advanced_farm_fight_blip)
    RemoveBlip(advanced_zombie_blip)
    RemoveBlip(advanced_sumo_blip)
    RemoveBlip(advanced_parkour_blip)
    RemoveBlip(advanced_snowball_blip)
    RemoveBlip(advanced_knife_blip)
    RemoveBlip(farm_and_fight_safe_1_blip)
    RemoveBlip(farm_and_fight_safe_2_blip)
    RemoveBlip(farm_and_fight_safe_3_blip)
    RemoveBlip(farm_and_fight_safe_4_blip)
    RemoveBlip(farm_and_fight_safe_5_blip)
    RemoveBlip(farm_and_fight_safe_6_blip)
    RemoveBlip(farm_and_fight_safe_7_blip)
    RemoveBlip(farm_and_fight_safe_1_main_blip)
    RemoveBlip(farm_and_fight_safe_2_main_blip)
    RemoveBlip(farm_and_fight_safe_3_main_blip)
    RemoveBlip(farm_and_fight_safe_4_main_blip)
    RemoveBlip(farm_and_fight_safe_5_main_blip)
    RemoveBlip(farm_and_fight_safe_6_main_blip)
    RemoveBlip(farm_and_fight_safe_7_main_blip)
    RemoveBlip(priv_lobby_madde_x_blip)
end